### ISSUE TITLE
Can't open file.jpg

### ISSUE THREAD

**Issue by amirtronix** [aphyt/omron#2]
I tried saving a .jpg image with 

```
from omron import f4_tcp_serial


if __name__ == '__main__':
    f4_instance = f4_tcp_serial.F4TCPSerial()
    f4_instance.connect('192.168.250.15')
    f4_instance.get_image('file.jpg')
    f4_instance.close()
```

But can't open the saved image.

<img width="626" alt="Screenshot 2024-07-15 082442" src="https://github.com/user-attachments/assets/d51ad814-c5fa-4ff5-a4d1-b94b12dacd30">

**Comment by aphyt** [comment]
Are you triggering an inspection? Can you verify that you that your F4 vision system is at that IP address?
